name = "personal-blog"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB" # 绑定的变量名，在代码中使用
database_name = "personal-blog-db"
database_id = "cb89ea0b-22d5-400c-991b-261b73de07cd" # 部署时需要替换

[[r2_buckets]]
binding = "BLOG_BUCKET"
bucket_name = "personal-blog-bucket"
