name = "personal-blog-workers"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
BLOG_TITLE = "我的个人博客"

[[d1_databases]]
binding = "DB"
database_name = "personal-blog-db"
database_id = "cb89ea0b-22d5-400c-991b-261b73de07cd"

# 注释掉 R2 配置，暂时不使用
# [[r2_buckets]]
# binding = "BLOG_BUCKET"
# bucket_name = "personal-blog-bucket"
